#!/bin/bash

if [ -f .listener_pids ]; then
    echo killing old listeners...
    while read p; do 
	echo killing $p
	kill $p
    done < .listener_pids
    rm .listener_pids;
else
    echo cannot find pid file for listeners;
fi
