# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='expertsrc.proto',
  package='',
  serialized_pb='\n\x0f\x65xpertsrc.proto\"\x8f\x03\n\rQuestionBatch\x12!\n\x04type\x18\x01 \x02(\x0e\x32\x13.QuestionBatch.Type\x12\x12\n\nasker_name\x18\x02 \x01(\t\x12\x13\n\x0bsource_name\x18\x03 \x01(\t\x12)\n\x08question\x18\x04 \x03(\x0b\x32\x17.QuestionBatch.Question\x1a\xe1\x01\n\x08Question\x12\x13\n\x0b\x64omain_name\x18\x01 \x01(\t\x12.\n\x06\x63hoice\x18\x02 \x03(\x0b\x32\x1e.QuestionBatch.Question.Choice\x12\x16\n\x0elocal_field_id\x18\x03 \x01(\x05\x12\x18\n\x10local_field_name\x18\x04 \x01(\t\x1a^\n\x06\x43hoice\x12\x1b\n\x13global_attribute_id\x18\x01 \x01(\x05\x12\x1d\n\x15global_attribute_name\x18\x02 \x01(\t\x12\x18\n\x10\x63onfidence_score\x18\x03 \x01(\x02\"#\n\x04Type\x12\r\n\tSCHEMAMAP\x10\x01\x12\x0c\n\x08TRAINING\x10\x02\"\x86\x02\n\x0b\x41nswerBatch\x12\x1f\n\x04type\x18\x01 \x02(\x0e\x32\x11.AnswerBatch.Type\x12#\n\x06\x61nswer\x18\x02 \x03(\x0b\x32\x13.AnswerBatch.Answer\x1a\x8b\x01\n\x06\x41nswer\x12\x13\n\x0b\x61nswerer_id\x18\x01 \x01(\x05\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x11\n\tauthority\x18\x03 \x01(\x02\x12\x1b\n\x13global_attribute_id\x18\x04 \x01(\x05\x12\x16\n\x0elocal_field_id\x18\x05 \x01(\x05\x12\x10\n\x08is_match\x18\x06 \x01(\x08\"#\n\x04Type\x12\r\n\tSCHEMAMAP\x10\x01\x12\x0c\n\x08TRAINING\x10\x02\"\xf7\x01\n\x0bReviewBatch\x12\x1f\n\x04type\x18\x01 \x02(\x0e\x32\x11.ReviewBatch.Type\x12#\n\x06review\x18\x02 \x03(\x0b\x32\x13.ReviewBatch.Review\x1a}\n\x06Review\x12\x13\n\x0breviewer_id\x18\x01 \x01(\x05\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x11\n\tauthority\x18\x03 \x01(\x02\x12\x11\n\tanswer_id\x18\x04 \x01(\x05\x12\x12\n\nis_correct\x18\x05 \x01(\x05\x12\x10\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x06 \x01(\t\"#\n\x04Type\x12\r\n\tSCHEMAMAP\x10\x01\x12\x0c\n\x08TRAINING\x10\x02')



_QUESTIONBATCH_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='QuestionBatch.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SCHEMAMAP', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TRAINING', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=384,
  serialized_end=419,
)

_ANSWERBATCH_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='AnswerBatch.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SCHEMAMAP', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TRAINING', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=384,
  serialized_end=419,
)

_REVIEWBATCH_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='ReviewBatch.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='SCHEMAMAP', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TRAINING', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=384,
  serialized_end=419,
)


_QUESTIONBATCH_QUESTION_CHOICE = descriptor.Descriptor(
  name='Choice',
  full_name='QuestionBatch.Question.Choice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='global_attribute_id', full_name='QuestionBatch.Question.Choice.global_attribute_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='global_attribute_name', full_name='QuestionBatch.Question.Choice.global_attribute_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='confidence_score', full_name='QuestionBatch.Question.Choice.confidence_score', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=288,
  serialized_end=382,
)

_QUESTIONBATCH_QUESTION = descriptor.Descriptor(
  name='Question',
  full_name='QuestionBatch.Question',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='domain_name', full_name='QuestionBatch.Question.domain_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='choice', full_name='QuestionBatch.Question.choice', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='local_field_id', full_name='QuestionBatch.Question.local_field_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='local_field_name', full_name='QuestionBatch.Question.local_field_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_QUESTIONBATCH_QUESTION_CHOICE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=157,
  serialized_end=382,
)

_QUESTIONBATCH = descriptor.Descriptor(
  name='QuestionBatch',
  full_name='QuestionBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='QuestionBatch.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='asker_name', full_name='QuestionBatch.asker_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='source_name', full_name='QuestionBatch.source_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='question', full_name='QuestionBatch.question', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_QUESTIONBATCH_QUESTION, ],
  enum_types=[
    _QUESTIONBATCH_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=419,
)


_ANSWERBATCH_ANSWER = descriptor.Descriptor(
  name='Answer',
  full_name='AnswerBatch.Answer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='answerer_id', full_name='AnswerBatch.Answer.answerer_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='confidence', full_name='AnswerBatch.Answer.confidence', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='authority', full_name='AnswerBatch.Answer.authority', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='global_attribute_id', full_name='AnswerBatch.Answer.global_attribute_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='local_field_id', full_name='AnswerBatch.Answer.local_field_id', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_match', full_name='AnswerBatch.Answer.is_match', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=508,
  serialized_end=647,
)

_ANSWERBATCH = descriptor.Descriptor(
  name='AnswerBatch',
  full_name='AnswerBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='AnswerBatch.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='answer', full_name='AnswerBatch.answer', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ANSWERBATCH_ANSWER, ],
  enum_types=[
    _ANSWERBATCH_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=422,
  serialized_end=684,
)


_REVIEWBATCH_REVIEW = descriptor.Descriptor(
  name='Review',
  full_name='ReviewBatch.Review',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='reviewer_id', full_name='ReviewBatch.Review.reviewer_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='confidence', full_name='ReviewBatch.Review.confidence', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='authority', full_name='ReviewBatch.Review.authority', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='answer_id', full_name='ReviewBatch.Review.answer_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_correct', full_name='ReviewBatch.Review.is_correct', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='feedback', full_name='ReviewBatch.Review.feedback', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=772,
  serialized_end=897,
)

_REVIEWBATCH = descriptor.Descriptor(
  name='ReviewBatch',
  full_name='ReviewBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='ReviewBatch.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='review', full_name='ReviewBatch.review', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_REVIEWBATCH_REVIEW, ],
  enum_types=[
    _REVIEWBATCH_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=687,
  serialized_end=934,
)

_QUESTIONBATCH_QUESTION_CHOICE.containing_type = _QUESTIONBATCH_QUESTION;
_QUESTIONBATCH_QUESTION.fields_by_name['choice'].message_type = _QUESTIONBATCH_QUESTION_CHOICE
_QUESTIONBATCH_QUESTION.containing_type = _QUESTIONBATCH;
_QUESTIONBATCH.fields_by_name['type'].enum_type = _QUESTIONBATCH_TYPE
_QUESTIONBATCH.fields_by_name['question'].message_type = _QUESTIONBATCH_QUESTION
_QUESTIONBATCH_TYPE.containing_type = _QUESTIONBATCH;
_ANSWERBATCH_ANSWER.containing_type = _ANSWERBATCH;
_ANSWERBATCH.fields_by_name['type'].enum_type = _ANSWERBATCH_TYPE
_ANSWERBATCH.fields_by_name['answer'].message_type = _ANSWERBATCH_ANSWER
_ANSWERBATCH_TYPE.containing_type = _ANSWERBATCH;
_REVIEWBATCH_REVIEW.containing_type = _REVIEWBATCH;
_REVIEWBATCH.fields_by_name['type'].enum_type = _REVIEWBATCH_TYPE
_REVIEWBATCH.fields_by_name['review'].message_type = _REVIEWBATCH_REVIEW
_REVIEWBATCH_TYPE.containing_type = _REVIEWBATCH;
DESCRIPTOR.message_types_by_name['QuestionBatch'] = _QUESTIONBATCH
DESCRIPTOR.message_types_by_name['AnswerBatch'] = _ANSWERBATCH
DESCRIPTOR.message_types_by_name['ReviewBatch'] = _REVIEWBATCH

class QuestionBatch(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Question(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    
    class Choice(message.Message):
      __metaclass__ = reflection.GeneratedProtocolMessageType
      DESCRIPTOR = _QUESTIONBATCH_QUESTION_CHOICE
      
      # @@protoc_insertion_point(class_scope:QuestionBatch.Question.Choice)
    DESCRIPTOR = _QUESTIONBATCH_QUESTION
    
    # @@protoc_insertion_point(class_scope:QuestionBatch.Question)
  DESCRIPTOR = _QUESTIONBATCH
  
  # @@protoc_insertion_point(class_scope:QuestionBatch)

class AnswerBatch(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Answer(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ANSWERBATCH_ANSWER
    
    # @@protoc_insertion_point(class_scope:AnswerBatch.Answer)
  DESCRIPTOR = _ANSWERBATCH
  
  # @@protoc_insertion_point(class_scope:AnswerBatch)

class ReviewBatch(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Review(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _REVIEWBATCH_REVIEW
    
    # @@protoc_insertion_point(class_scope:ReviewBatch.Review)
  DESCRIPTOR = _REVIEWBATCH
  
  # @@protoc_insertion_point(class_scope:ReviewBatch)

# @@protoc_insertion_point(module_scope)
